name: Upload Image
description: Composite action for uploading built images

inputs:
  target:
    description: Directory where config.yaml is generated
    required: true
  release:
    description: Image release name
    required: true
  release_aliases:
    description: Image release aliases as a list of release=aliases pairs.
    default: ""
  requirements:
    description: Image requirements as a list of key=value pairs.
    default: ""

runs:
  using: composite
  steps:
    - name: Generate config.yaml
      shell: bash
      env:
        TARGET: "${{ inputs.target }}"
        RELEASE: "${{ inputs.release }}"
        RELEASE_ALIASES: "${{ inputs.release_aliases }}"
        REQUIREMENTS: "${{ inputs.requirements }}"
      run: |
        # Expand target path.
        TARGET=$(echo "${TARGET}")
        CONFIG="${TARGET}/config.yaml"

        mkdir -p "${TARGET}"

        # Config release aliases.
        aliases=$(echo "${RELEASE_ALIASES}" | grep -w "^${RELEASE}" | cut -d '=' -f2- | tr -d ' ')
        if [ -n "${aliases}" ]; then
            echo "release_aliases: ${aliases}" >> ${CONFIG}
        fi

        # Config requirements.
        if [ -n "${REQUIREMENTS}" ]; then
            echo "requirements:" >> ${CONFIG}

            # Remove spaces, replace equal sign (=) with semi colon (:) and
            # add two leading spaces.
            echo "${REQUIREMENTS}" | sed 's/^ *\([^ ]\+\) *= */  \1: /' >> ${CONFIG}
        fi

        cat ${CONFIG} 2>/dev/null || true
