name: Setup Environment
description: Composite action that sets up the environment for building and testing images

inputs:
  lxd-channel:
    description: LXD snap channel to install
    default: 5.21/stable
  lxd-imagebuilder-channel:
    description: LXD imagebuilder snap channel to install
    default: latest/edge
  # go-version:
  #   description: Go version to install
  #   default: 1.22.x

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
            btrfs-progs \
            build-essential \
            ca-certificates \
            curl \
            debootstrap \
            dirmngr \
            dosfstools \
            gcc \
            gdisk \
            git \
            gpg \
            gpg-agent \
            kpartx \
            libc6-dev \
            libncurses-dev \
            make \
            mawk \
            patch \
            python3 \
            qemu-utils \
            rsync \
            squashfs-tools \
            unzip \
            xz-utils \
            zstd

    - name: Setup LXD Imagebuilder ${{ inputs.lxd-imagebuilder-channel }}
      shell: bash
      run: |
        sudo snap install lxd-imagebuilder --channel=${{ inputs.lxd-imagebuilder-channel }}
        lxd-imagebuilder --version

    - name: Setup LXD ${{ inputs.lxd-channel }}
      shell: bash
      run: |
        sudo snap refresh lxd --channel=${{ inputs.lxd-channel }}
        sudo lxd waitready --timeout 60
        sudo chmod 777 /var/snap/lxd/common/lxd/unix.socket
        sudo lxd init --auto
        lxc version

    - name: Print supported LXD drivers
      shell: bash
      run: |
        lxc query /1.0 | jq '.environment.driver'
        sudo lxc query /1.0 | jq '.environment.driver'
