name: Upload Image
description: Composite action for uploading built images

inputs:
  target:
    description: Directory where built image is located
    required: true
  image_dir:
    description: Image directory in format <distro>/<release>/<arch>/<variant>
    required: true
  ssh_private_key:
    description: SSH private key for the image server
    required: true

runs:
  using: composite
  steps:
    - name: Configure private key and known host
      shell: bash
      env:
        SSH_HOST: images.lxd.canonical.com
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
      run: |
        # Store image server private key.
        mkdir -p -m 0700 ~/.ssh
        ssh-agent -a "${SSH_AUTH_SOCK}" > /dev/null
        ssh-add - <<< "${SSH_PRIVATE_KEY}"
        ssh-add -L > ~/.ssh/id_ed25519.pub

        # Configure known host.
        echo "${SSH_HOST} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkbjXwS373I8wGmlblwjh6NdFalP8wgK8kilCbuoI6e" >> ~/.ssh/known_hosts

    - name: Upload artifacts to the image server
      shell: bash
      env:
        SSH_HOST: images.lxd.canonical.com
        SSH_USER: imageserver
        SSH_PORT: 922
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SRC_DIR: ${{ inputs.target }}
        IMG_DIR: ${{ inputs.image_dir }}
      run: |
        set -eux

        # FIXME: needed to expand despite the single quotes: '${HOME}/build'
        SRC_DIR="$(eval echo "${SRC_DIR}")"

        # Print artifacts
        ls -lah "${SRC_DIR}"

        # Ensure path of the source directory is expanded.
        VERSION="$(cat "${SRC_DIR}/serial")"

        # Create directory structure that will be mirrored on the target server.
        mkdir -p "${SRC_DIR}-upload/${IMG_DIR}/.${VERSION}"
        mv "${SRC_DIR}"/* "${SRC_DIR}-upload/${IMG_DIR}/.${VERSION}"

        # First upload contents to the temporary dir and once fully uploaded
        # move the directory to the final destination to avoid potential race
        # where simplestream-maintainer includes partially uploaded images.
        sftp -oHostKeyAlgorithms=ssh-ed25519 -P ${SSH_PORT} -oConnectionAttempts=10 -oConnectTimeout=10 -b - "${SSH_USER}@${SSH_HOST}" <<EOF
            put -R "${SRC_DIR}"-upload/*
            rename "${IMG_DIR}/.${VERSION}" "${IMG_DIR}/${VERSION}"
            bye
        EOF
