name: Upload Image
description: Composite action for uploading built images

inputs:
  # image_name:
  #   description: Final image name
  #   required: true
  image_dir:
    description: Directory where built image is located
    required: true
  ssh_ip:
    description: SSH IP of the image server
    required: true
  ssh_port:
    description: SSH port of the image server
    required: true
  ssh_user:
    description: SSH user of the image server
    required: true
  ssh_private_key:
    description: SSH private key for the image server
    required: true

runs:
  using: composite
  steps:
    - name: Print artifacts
      shell: bash
      run: ls -lah "${{ inputs.image_dir }}"

    - name: Configure private key and known host
      shell: bash
      env:
        SSH_IP: ${{ inputs.ssh_ip }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run : |
        # Store image server private key.
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/imageserver_id_rsa
        chmod 600 ~/.ssh/imageserver_id_rsa

        # Configure known host.
        ssh-keyscan -H -p ${SSH_PORT} ${SSH_IP} >> ~/.ssh/known_hosts

    - name: Rsync artifacts to the image server
      shell: bash
      env:
        SSH_IP: ${{ inputs.ssh_ip }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        # Ensure path of the source directory is expanded.
        SRC_DIR=$(echo ${{ inputs.image_dir }})

        # DST_DIR=${{ inputs.image_name }}
        # VERSION=$(cat "${SRC_DIR}/serial")

        # Replicate destination directory structure.
        # mkdir -p "${SRC_DIR}-upload/${DST_DIR}/${VERSION}"
        # mv ${SRC_DIR}/* "${SRC_DIR}-upload/${DST_DIR}/${VERSION}/"

        # s -> Uses SFTP protocol
        # r -> Copies files recursively
        # p -> Preserves modification and access times
        # C -> Enables compression
        #
        scp -srpC -v -P ${SSH_PORT} -i ~/.ssh/imageserver_id_rsa \
          ${SRC_DIR}/* \
          "${SSH_USER}@${SSH_IP}:."

        # rsync \
        #   --archive \
        #   --verbose \
        #   --compress \
        #   --mkpath \
        #   --rsh "ssh -p ${SSH_PORT} -i ~/.ssh/imageserver_id_rsa" \
        #   "${SRC_DIR}/" "${SSH_USER}@${SSH_IP}:${DST_DIR}/${VERSION}"
