name: Upload Image
description: Composite action for uploading built images

inputs:
  target:
    description: Directory where built image is located
    required: true
  image_dir:
    description: Image directory in format <distro>/<release>/<arch>/<variant>
    required: true
  ssh_ip:
    description: SSH IP of the image server
    required: true
  ssh_port:
    description: SSH port of the image server
    required: true
  ssh_user:
    description: SSH user of the image server
    required: true
  ssh_private_key:
    description: SSH private key for the image server
    required: true

runs:
  using: composite
  steps:
    - name: Print artifacts
      shell: bash
      run: ls -lah "${{ inputs.target }}"

    - name: Configure private key and known host
      shell: bash
      env:
        SSH_IP: ${{ inputs.ssh_ip }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run : |
        # Store image server private key.
        mkdir -p -m 0700 ~/.ssh
        touch ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_ed25519

        # Configure known host.
        ssh-keyscan -H -p ${SSH_PORT} ${SSH_IP} >> ~/.ssh/known_hosts

    - name: Rsync artifacts to the image server
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_ip }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        # Ensure path of the source directory is expanded.
        SRC_DIR=$(echo ${{ inputs.target }})
        IMG_DIR=${{ inputs.image_dir }}
        VERSION=$(cat "${SRC_DIR}/serial")

        # First upload contents to the temporary dir and once fully uploaded
        # move the directory to the final destination to avoid potential race
        # where simplestream-maintainer includes partially uploaded images.
        TMP_DIR="${IMG_DIR}/.${VERSION}"
        DST_DIR="${IMG_DIR}/${VERSION}"

        # Create directory structure that will be mirrored on the target server.
        mkdir -p "${SRC_DIR}-upload/${TMP_DIR}"
        mv ${SRC_DIR}/* "${SRC_DIR}-upload/${TMP_DIR}"

        # Use SFTP to upload images to the server.
        sftp -P ${SSH_PORT} "${SSH_USER}@${SSH_HOST}" <<EOF
            put -r ${SRC_DIR}-upload/*
            rename "${TMP_DIR}" "${DST_DIR}"
            bye
        EOF
