name: Upload Image
description: Composite action for uploading built images

inputs:
  image_name:
    description: Final image name
    required: true
  image_dir:
    description: Directory where built image is located
    required: true
  ssh_ip:
    description: SSH IP of the image server
    required: true
  ssh_port:
    description: SSH port of the image server
    required: true
  ssh_user:
    description: SSH user of the image server
    required: true
  ssh_private_key:
    description: SSH private key for the image server
    required: true
  ssh_base_dir:
    description: SSH base destination directory on the image server
    required: true
  # types:
  #   description: Image types
  #   required: true

runs:
  using: composite
  steps:
      # actions/upload-artifact does not expand env vars.
    - name: Expand target path
      shell: bash
      run: echo "image_dir=${{ inputs.image_dir }}" >> $GITHUB_ENV

    - name: Print artifacts
      shell: bash
      run: ls -lah "${{ env.image_dir }}"

    # - name: Publish artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "${{ inputs.name }}"
    #     path: |
    #       ${{ env.target }}/*.qcow2
    #       ${{ env.target }}/*.squashfs
    #       ${{ env.target }}/*.tar.xz
    #       ${{ env.target }}/image.yaml
    #       ${{ env.target }}/serial
    #     if-no-files-found: "error"
    #     retention-days: 1
    #     compression-level: 0
    #     overwrite: true

    - name: Rsync artifacts to the image server
      shell: bash
      run: |
        set -e

        SRC_DIR="${{ env.image_dir }}"
        DST_DIR="${{ inputs.ssh_base_dir }}/images/${{ inputs.name }}"

        SERIAL=$(cat "${SRC_DIR}/serial")

        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/imageserver_id_rsa
        chmod 600 ~/.ssh/imageserver_id_rsa
        ssh-keyscan -H -p ${{ inputs.ssh_port }} ${{ inputs.ssh_ip }} >> ~/.ssh/known_hosts

        rsync \
          -avz \
          -e "ssh -p ${{ inputs.ssh_port }} -i ~/.ssh/imageserver_id_rsa" \
          "${SRC_DIR}" \
          "${{ inputs.ssh_user }}@${{ inputs.ssh_ip }}:${DST_DIR}/${SERIAL}"
