name: Test Image
description: Composite action for testing built image

inputs:
  target:
    description: Directory where built image is located
    required: true
  distro:
    description: Image distribution
    required: true
  release:
    description: Image release
    required: true
  variant:
    description: Image variant
    required: true
  type:
    description: Image type [container, vm]
    required: true

runs:
  using: composite
  steps:
    - name: Test image
      shell: bash
      run: |
        TYPE=${{ inputs.type }}
        TARGET=${{ inputs.target }}
        DISTRO=${{ inputs.distro }}
        RELEASE=${{ inputs.release }}
        VARIANT=${{ inputs.variant }}

        set -eux

        TEST_ID="${DISTRO}-${RELEASE}-${VARIANT} (${TYPE})"
        echo "==> TEST: ${TEST_ID}"

        VIRT_ENABLED=$(lxc query /1.0 | jq '.environment.driver | contains("qemu")')
        if [ "${TYPE}" = "vm" ] && [ "${VIRT_ENABLED}" != "true" ]; then
            echo "==> FAIL: Virtualization is not supported"
            exit 1
        fi

        if ./bin/test-image "${TYPE}" "${DISTRO}" "${RELEASE}" "${VARIANT}" "${TARGET}"; then
            echo "==> PASS: ${TEST_ID}"
            exit 0
        fi

        echo "==> FAIL: ${TEST_ID}"
        exit 1

    - name: Upload as CI artifacts images that failed QA (manual || retries)
      if: failure() && (github.run_attempt != 1 || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: broken-images-${{ inputs.distro }}-${{ inputs.release }}-${{ inputs.variant }}
        path: ~/build/
        retention-days: 1
        if-no-files-found: ignore
        compression-level: 0
        overwrite: true
