name: Build Linux Mint Images

on:
  # workflow_dispatch:
  # workflow_call:
  #   inputs:
  #     publish:
  #       type: boolean
  #       default: false
  #       description: Publish built image
  push:

jobs:
  mint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - ulyana
          - ulyssa
          - uma
          # - una
          # - vanessa
          - vera
          - victoria
        variant:
          - default
          - cloud
        architecture:
          - amd64
    env:
      type: "container"
      distro: "${{ github.job }}"
      target: "${HOME}/build"

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/image-setup
        with:
          deploy-key: ${{ secrets.GH_KEY }}

      - name: Build image
        run: |
          TIMEOUT=1800
          YAML="${{ github.workspace }}/images/${{ env.distro }}.yaml"
          ARCH="${{ matrix.architecture }}"
          TYPE="${{ env.type }}"
          RELEASE="${{ matrix.release}}"

          SUITE="jammy"
          if [ "${RELEASE}" = "ulyana" ] || [ "${RELEASE}" = "ulyssa" ] || [ "${RELEASE}" = "uma" ] || [ "${RELEASE}" = "una" ]; then
              SUITE=focal
          fi

          ./bin/build-distro "${YAML}" "${ARCH}" "${TYPE}" "${TIMEOUT}" "${{ env.target }}" \
              -o image.architecture="${ARCH}" \
              -o image.release=${{ matrix.release }} \
              -o image.variant=${{ matrix.variant }} \
              -o source.suite="${SUITE}"

      - name: Print build artifacts
        run: ls -lah "${{ env.target }}"

      - name: Test container image
        uses: ./.github/actions/image-test
        if: contains(env.type, 'container')
        with:
          type: container
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}

      - name: Test VM image
        uses: ./.github/actions/image-test
        if: contains(env.type, 'vm')
        with:
          type: vm
          target: ${{ env.target }}
          distro: ${{ env.distro }}
          release: ${{ matrix.release }}
          variant: ${{ matrix.variant }}
