name: Test config

on:
  push:

jobs:
  image-config:
    runs-on: ubuntu-latest
    env:
      type: "container"
      distro: "${{ github.job }}"
      target: "${HOME}/build"
      release_aliases: |
        12=bookworm
        13=trixie

    steps:
      - uses: actions/checkout@v4

      - name: Test image config
        uses: ./.github/actions/image-config
        with:
          target: "${{ env.target }}"
          release: bookworm
          image_release_aliases: |-
            bullseye = 11
            bookworm = 12
            trixie   = 13
          image_requirements: |-
            secure_boot=false
            custom_key = true

