name: Submit a test job to Testflinger
on:
  workflow_dispatch:

jobs:
  testflinger-submit:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bypass aproxy for testflinger.canonical.com host
        uses: ./.github/actions/set-aproxy-bypass-for-testflinger

      - name: Submit job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job: |
              job_queue: hp-elitebook-850-g7-notebook-pc
              test_data:
                  test_cmds: |
                      #!/usr/bin/env bash
                      set -x
                      ls -alR
